import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Dev Chat',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClerkProvider
        // appearance={{
        //   variables:{
        //     colorBackground:"#000",
        //     colorText:"#fff",
        //     colorInputBackground:"#000",
        //     colorInputText:"#fff",
        //     colorWarning:"#ff0303"
        //   }
        // }}
        >{children}</ClerkProvider>
      </body>
    </html>
  );
}
